# Generated by Django 2.2.9 on 2020-01-20 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dex', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detail',
            new_name='Pokemon',
        ),
    ]
